//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentalCarMvcProject.Models.EntityFramework
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Cars
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cars()
        {
            this.CarImages = new HashSet<CarImages>();
            this.Rentals = new HashSet<Rentals>();
        }
    
        public int Id { get; set; }
        [Display(Name ="BranName")]
        [Required(ErrorMessage ="BrandName boþ geçilemez")]
        public Nullable<int> BrandId { get; set; }
        [Display(Name = "ColorName")]
        [Required(ErrorMessage = "ColorName boþ geçilemez")]
        public Nullable<int> ColorId { get; set; }
        [Required(ErrorMessage = "ModelYear boþ geçilemez")]
        public Nullable<int> ModelYear { get; set; }
        [Required(ErrorMessage = "DailyPrice boþ geçilemez")]
        public Nullable<int> DailyPrice { get; set; }
        [Required(ErrorMessage = "Descriptions boþ geçilemez")]
        public string Descriptions { get; set; }
    
        public virtual Brands Brands { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CarImages> CarImages { get; set; }
        public virtual Colors Colors { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Rentals> Rentals { get; set; }
    }
}
