//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentalCarMvcProject.Models.EntityFramework
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Rentals
    {
        public int Id { get; set; }
        [Display(Name ="CarName")]
        [Required(ErrorMessage ="CarName boþ geçilemez")]
        public Nullable<int> CarId { get; set; }
        [Display(Name = "CustomerName")]
        [Required(ErrorMessage = "CustomerName boþ geçilemez")]
        public Nullable<int> CustomerId { get; set; }
        public Nullable<System.DateTime> RentDate { get; set; }
        public Nullable<System.DateTime> ReturnDate { get; set; }
    
        public virtual Cars Cars { get; set; }
        public virtual Customers Customers { get; set; }
    }
}
